### ISSUE TITLE
Syntax highlight does not work

### ISSUE THREAD

**Issue by janmasrovira** [emacsorphanage/gnuplot#67] opened 2020-12-19 09:18 UTC
Hi,
just a few days ago everything was working smoothly. However, recently I have noticed that when I open a gnuplot file with gnuplot-mode activated, the code is not colored anymore.
Any idea of what could cause this issue?

I use spacemacs (develop branch), gnuplot 5.4 and gnuplot-mode 0.7.

Thanks for all the work!
cheers

**Comment by mtreca** [comment] 2020-12-19 12:39
Thanks a lot for reporting this issue.

There has been quite a few changes recently indeed, commit 62117fe might be responsible. I will investigate this today.

Do you get any error messages or warnings when starting gnuplot mode?

**Comment by janmasrovira** [comment] 2020-12-19 12:55
Thanks for the swif treply. I don't get any error. FYI I have the following in my config file:

```
  (setq gnuplot-program "/usr/local/bin/gnuplot")
  (setq gnuplot-program-version "5.4")
  (setq gnuplot-program-major-version 5)
  (setq gnuplot-program-minor-version 4)
```
I added this because otherwise I got a warning that gnuplot-mode could not guess which version of gnuplot I was using.

**Comment by mtreca** [comment] 2020-12-19 13:25
I found the cause of the issue. I just pushed a fix to master, could you try why the latest version?

Regarding your configuration, I don't like the fact that version configuration has to be done manually. I'm thinking about removing version numbers altogether, or at least fixing the way they are fetched to that manual configuration is not needed. More info on PR #63 if you are interested!

**Closed** 2020-12-19 14:08 UTC

**Comment by janmasrovira** [comment] 2020-12-19 14:11
I have tried with the master branch and it works!
